### ISSUE TITLE
ข้อมูลการทำ Wiki ของทีมใน week ที่ 2

### ISSUE THREAD

**Issue by up1** [konlawatit/SWDEV-BBP-PLUS#3]
It62070071 <54878356+It62070071@users.noreply.github.com>:
	  insertions:    206	(35%)
	  deletions:     102	(33%)
	  files:         11	(14%)
	  commits:       11	(14%)
	  lines changed: 308	(34%)
	  first commit:  Sun Jan 16 01:00:51 2022 +0700
	  last commit:   Sun Jan 23 02:14:17 2022 +0700

	 bb0b <59884776+konlawatit@users.noreply.github.com>:
	  insertions:    60	(10%)
	  deletions:     12	(4%)
	  files:         8	(10%)
	  commits:       8	(10%)
	  lines changed: 72	(8%)
	  first commit:  Sat Jan 15 23:16:32 2022 +0700
	  last commit:   Sun Jan 23 02:51:24 2022 +0700

	 Pando5 <80274964+Pando5@users.noreply.github.com>:
	  insertions:    75	(13%)
	  deletions:     37	(12%)
	  files:         13	(16%)
	  commits:       13	(16%)
	  lines changed: 112	(12%)
	  first commit:  Sat Jan 15 21:51:14 2022 +0700
	  last commit:   Sun Jan 23 17:34:01 2022 +0700

	 it62070033 <57473952+it62070033@users.noreply.github.com>:
	  insertions:    57	(10%)
	  deletions:     26	(8%)
	  files:         18	(23%)
	  commits:       19	(24%)
	  lines changed: 83	(9%)
	  first commit:  Sat Jan 15 21:37:39 2022 +0700
	  last commit:   Sun Jan 23 13:52:39 2022 +0700

	 Yannawut62070051 <56510625+Yannawut62070051@users.noreply.github.com>:
	  insertions:    61	(10%)
	  deletions:     98	(32%)
	  files:         14	(18%)
	  commits:       14	(18%)
	  lines changed: 159	(18%)
	  first commit:  Sat Jan 15 22:12:41 2022 +0700
	  last commit:   Sun Jan 23 13:04:48 2022 +0700

	 ball9989 <56550273+ball9989@users.noreply.github.com>:
	  insertions:    130	(22%)
	  deletions:     33	(11%)
	  files:         15	(19%)
	  commits:       14	(18%)
	  lines changed: 163	(18%)
	  first commit:  Mon Jan 10 15:07:38 2022 +0700
	  last commit:   Sun Jan 23 02:31:40 2022 +0700

**Comment by Yannawut62070051** [comment]
ขอบคุณครับ
